### ISSUE TITLE
Failed scanning person (ID '16854') data with scanner tmdb

### ISSUE THREAD

**Issue by modmax** [Omertron/api-themoviedb#26]
Following error occures for persons, i.e. for ID 16854

java.lang.NullPointerException
at com.omertron.themoviedbapi.methods.TmdbPeople.getPersonInfo(TmdbPeople.java:83)
at com.omertron.themoviedbapi.TheMovieDbApi.getPersonInfo(TheMovieDbApi.java:1157)

**Comment by modmax** [comment]
Problem is: if "appendToResponse" is null, then the check if "atr" contains something fails wth a null pointer exception.
