### ISSUE TITLE
java.lang.NoClassDefFoundError: Failed resolution of: Lorg/apache/http/impl/client/HttpClientBuilder

### ISSUE THREAD

**Issue by gulkush** [Omertron/api-themoviedb#37]
I am using gradle dependency 'com.omertron:themoviedbapi:4.2' in my Android Studio Project. Here is my stacktrace.

Process: com.softkoki.myapplication, PID: 7180
    java.lang.RuntimeException: An error occurred while executing doInBackground()
            at android.os.AsyncTask$3.done(AsyncTask.java:309)
            at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
            at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
            at java.util.concurrent.FutureTask.run(FutureTask.java:242)
            at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
            at java.lang.Thread.run(Thread.java:818)
     Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Lorg/apache/http/impl/client/HttpClientBuilder;
            at org.yamj.api.common.http.SimpleHttpClientBuilder.build(SimpleHttpClientBuilder.java:190)
            at com.omertron.themoviedbapi.TheMovieDbApi.<init>(TheMovieDbApi.java:141)
            at com.softkoki.myapplication.MainActivity$FetchMovieTask.doInBackground(MainActivity.java:34)
            at com.softkoki.myapplication.MainActivity$FetchMovieTask.doInBackground(MainActivity.java:28)
            at android.os.AsyncTask$2.call(AsyncTask.java:295)
            at java.util.concurrent.FutureTask.run(FutureTask.java:237)
            at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
            at java.lang.Thread.run(Thread.java:818)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "org.apache.http.impl.client.HttpClientBuilder" on path: DexPathList[[zip file "/data/app/com.softkoki.myapplication-1/base.apk"],nativeLibraryDirectories=[/data/app/com.softkoki.myapplication-1/lib/arm, /vendor/lib, /system/lib]]
            at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
            at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
            at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
            at org.yamj.api.common.http.SimpleHttpClientBuilder.build(SimpleHttpClientBuilder.java:190)
            at com.omertron.themoviedbapi.TheMovieDbApi.<init>(TheMovieDbApi.java:141)
            at com.softkoki.myapplication.MainActivity$FetchMovieTask.doInBackground(MainActivity.java:34)
            at com.softkoki.myapplication.MainActivity$FetchMovieTask.doInBackground(MainActivity.java:28)
            at android.os.AsyncTask$2.call(AsyncTask.java:295)
            at java.util.concurrent.FutureTask.run(FutureTask.java:237)
            at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
            at java.lang.Thread.run(Thread.java:818)
    Suppressed: java.lang.ClassNotFoundException: org.apache.http.impl.client.HttpClientBuilder
            at java.lang.Class.classForName(Native Method)
            at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
            at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
            at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
            ... 11 more
     Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available

**Comment by gulkush** [comment]
Solved it.
I had include the following in my gradle file.
```
compile('com.omertron:themoviedbapi:4.2') {
        exclude group: 'org.apache.httpcomponents', module: 'httpclient'
        exclude module: 'junit'
    }
compile 'org.apache.httpcomponents:httpclient-android:4.3.5.1'
```

**Comment by ashish4rawat** [comment]
Someone Please help I am stuck

**Comment by ashish4rawat** [comment]
java.lang.NoClassDefFoundError: Failed resolution of: Lorg/apache/http/conn/scheme/SchemeRegistry;
        at com.loopj.android.http.AsyncHttpClient.getDefaultSchemeRegistry(AsyncHttpClient.java:182)
        at com.loopj.android.http.AsyncHttpClient.<init>(AsyncHttpClient.java:149)
        at com.loopj.android.http.AsyncHttpClient.<init>(AsyncHttpClient.java:119)

**Comment by humayuntanwar** [comment]
@ashish4rawat  i m getting the same error on android pie 9.0 , did you find any solution to this?

**Comment by vijaya06** [comment]
i m also getting the same error on android version 9.0
